POST http://localhost:3333/user
Content-Type: application/json

{
  "name": "King James",
  "email": "kj@gmail.com",
  "cpf": "07176378901123",
  "password": "123456"
}

###

//:payerId/:payeeId
POST http://localhost:3333/transaction/e9b952a5-0149-4084-9739-0c242161f509/61030954-11e2-4a9e-b1d2-e3dea34def4f
Content-Type: application/json

{
  "amount": 10
}

###

//:transactionId
Get http://localhost:3333/transaction/refound/fe924f7a-a216-4d0d-bf95-406e826296b0

###

//:userId
Get http://localhost:3333/user/transactions/61030954-11e2-4a9e-1232-e3dea34def4f

###
//:userId
Get http://localhost:3333/user/a793a89d-42eb-40fa-b7e0-8d5a75d0b355
